"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Client_1 = require('./http/Client');
exports.VLCClient = Client_1.VLCClient;
var Requester_1 = require('./http/Requester');
exports.getPlaylist = Requester_1.getPlaylist;
exports.getStatus = Requester_1.getStatus;
exports.command = Requester_1.command;
exports._request = Requester_1._request;
var vlcrc_1 = require('./util/vlcrc');
exports.editVLCRC = vlcrc_1.editVLCRC;
exports.VLCRC = vlcrc_1.VLCRC;
